build:
	xelatex -interaction=nonstopmode stacker.tex;
	xelatex -interaction=nonstopmode stacker.tex;
	rm stacker.aux stacker.bcf stacker.log stacker.run.xml stacker.toc stacker.fdb_latexmk stacker.fls